### PR TITLE
Use BATS Core on Travis

### PR DESCRIPTION
**Pull request by vincent-zurczak**

### CODE REVIEW

**Comment by vincent-zurczak** [comment]
Anyone to review this PR? :)
@bats-core/bats-detik

I commented the Docker build in Travis as Docker Hub limits downloads.

**Comment by vincent-zurczak** [comment]
@bats-core/bats-core @bats-core/bats-detik I cannot review nor approve my own PR (security settings).
Could any of you have a look please? This is blocking another PR.

**Review by martin-schulze-vireso — APPROVED** [review]
We moved core to GitHub actions because of the rate limit. Maybe that is possible for you too.

**Comment by vincent-zurczak** [comment]
Good idea. :+1: 
I will have a look on it. Thank you for the review.

**Pull request merged**
