### PR TITLE
Support using complex jsonpath as a property

### LINKED ISSUE #23: Passing a complex jsonpath as a property
Hey,

When passing a jsonpath like `.status.conditions[?(@.type=="Test")].name` with the following line
```
run try "at most 5 times every 2s to get custom-resource named site' and verify that '.status.conditions[?(@.type==\"Test\")].name' is 'ABC'"
```
doesn't work because, detik generates the client query as
`oc --namespace=test get custom-resource -o custom-columns=NAME:.metadata.name,PROP:.status.conditions[?(@.type==\"Test\")].name` 
which causes `error: unrecognized identifier Initialized` from the client.

This can simply fixed by passing the complex jsonpath in single quotes, which will make the client query 
`oc --namespace=test get custom-resource -o custom-columns=NAME:.metadata.name,PROP:'.status.conditions[?(@.type==\"Test\")].name'`

If we can agree on this I can create a PR (only requires changing [L266](https://github.com/bats-core/bats-detik/blob/master/lib/detik.bash#L266)) to fix this. Thanks! :smile:

### PR DESCRIPTION
**Pull request by rajula96reddy**
Fixes #23

### CODE REVIEW

**Comment by vincent-zurczak** [comment]
Hi,

The build on Travis failed, but I found out it was still using an old BATS version.
I have created #25 to solve it. Tests are successful with the last BATS version. Once this other PR is merged, I will integrate yours.

Thanks!

**Review by vincent-zurczak — APPROVED** [review]

**Comment by vincent-zurczak** [comment]
The other PR has been merged.
I have approved your changes, but this project (as well as other BATS projects) requires signed commits. Could you amend your commit and sign it? You can use `git commit -S --amend`. You will find more details in the following links:

* https://docs.github.com/en/github/authenticating-to-github/managing-commit-signature-verification/signing-commits
* https://docs.github.com/en/github/authenticating-to-github/managing-commit-signature-verification/generating-a-new-gpg-key
* https://docs.github.com/en/github/authenticating-to-github/managing-commit-signature-verification/telling-git-about-your-signing-key

You can also rebase from the master branch.
That will solve the continuous integration.

**Comment by rajula96reddy** [comment]
Hey @vincent-zurczak , I rebased and signed my commit. I also had to make one other change since the CI was failing. Can you please review the same?

**Review by vincent-zurczak — APPROVED** [review]

**Comment by vincent-zurczak** [comment]
Thank you @rajula96reddy. :+1:

**Pull request merged**
